<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/core.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-content/themes/customizr/assets/front/js/libs/fancybox/jquery.fancybox-1.3.4.min.js?ver=4.0.13'></script>
<script type='text/javascript'> </script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-content/themes/customizr/inc/assets/js/tc-scripts.min.js?ver=4.0.13'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/widget.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/tabs.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/accordion.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/mouse.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/resizable.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/draggable.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/button.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/position.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/dialog.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-includes/js/jquery/ui/sortable.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/?wpui-script=before&#038;ver=5.3.1'></script>
<script type='text/javascript'></script>
<script type='text/javascript' src='http://ahuacatlanavanza.gob.mx/wp-content/plugins/wp-ui/js/wp-ui.js?ver=0.8.8'></script>